Add /about, /credits pages with styling & layout
ten7/plantinfo pull request #1
Opened 2022-02-08 19:36 UTC by joshcesana

This PR adds:

- /about and /credits pages & content
- general-content layout & styling block
- update to critical.scss to include new styling block

2022-02-10 18:22 UTC, RainbowArray requested changes
Overall this looks really good from a code perspective, a few very minor notes I would recommend changing.

I have not done a visual review yet, but by my eye this looks like it will probably render well. Will double-check once code changes are complete.

Excellent work!

2022-02-10 18:22 UTC, RainbowArray commented on src/_includes/layouts/general-content.html
> +        <h1 class="[ page-title--general ]">{{ title }}</h1>
Probably good to have [ page-title ] on this as well to pull in general `page-title` styles, then override anything you need to override in the `--general` class.

2022-02-10 18:22 UTC, RainbowArray commented on src/about.md
> +
`AHL),and Richard T. Isaacson,`

to

`AHL), and Richard T. Isaacson,`

2022-02-10 18:22 UTC, RainbowArray commented on src/scss/blocks/_general-content.scss
> +  @include apply-utility('font', 'base');
Generally I recommend putting `@include` statements at the beginning of the ruleset, followed by other rules, which allows rules to override anything in the mixin.

2022-02-10 18:22 UTC, RainbowArray commented on src/scss/blocks/_general-content.scss
> +    font-size: 1em;
Prefer `rem` to `em`.

2022-02-10 18:22 UTC, RainbowArray commented on src/_includes/layouts/general-content.html
> +{% extends "layouts/base.html" %} {% block content %}
`{% block content %}` should go on the next line.

2022-02-10 19:28 UTC, joshcesana commented
All fixed. Great suggestions!

I'm now second guessing using a '--general' CSS block/selector, as I'm already needing to tweak it for the contact page. I may turn it into something more specific (--about or --credits) and also use a --contact in a future PR. 

Suggestions always welcome!

2022-02-10 22:20 UTC, RainbowArray commented
Tested this locally, and this is looking good. The one thing I would suggest is adding some generic link styles.

<img width="823" alt="Screen Shot 2022-02-10 at 4 16 27 PM" src="https://user-images.githubusercontent.com/1051098/153506077-2e13f924-e12a-42f7-91c9-26501a69d582.png">


If you look in `scss/blocks/_link.scss`, that is a good source of what to add.

I think you could basically take the styles from `.link` and apply those to an `a` element in general-content, so essentially:

`a {
  color: get-color('quinary-shade');
  text-decoration: none;

  &:hover,
  &:focus {
    text-decoration: underline;
  }
}`

Thanks!

2022-02-11 16:59 UTC, joshcesana commented
All done. Great suggestions once again. Looks great!

2022-02-11 19:32 UTC, RainbowArray commented
Looks great with the updated changes. Merging. Thanks!

2022-02-11 19:33 UTC, merged